### PR TITLE
Remove vscode settings

### PR DESCRIPTION
**Pull request by bartduisters**
@jennifer-shehane this PR only has the correct commit.

Remove settings for vscode. Add .vscode directory to gitignore. This way the styling of other people won't be overwritten by the settings.json in the vscode directory.

### CODE REVIEW

**Comment by jennifer-shehane** [comment]
Thanks for the contribution! Could you please sign our CLA?

**Comment by bartduisters** [comment]
> Thanks for the contribution! Could you please sign our CLA?

I am unable to sign it. It says 'succesfully signed' and then redirects me. Did this when opening the PR as well. I do notice that GitHub does not recognize the user I did the commit with. It tells me to add the e-mail address to my account. However, I cannot see the e-mail address linked to that account in the commit.

**Comment by jennifer-shehane** [comment]
@bartduisters The author of the commits sometimes does not match the email address on your GitHub account. Our CLA bot gets confused when they don't match. Here are some solutions to fixing when commits are linked to the wrong user: https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

**Comment by bahmutov** [comment]
I have decided against removing VSCode settings - I like them and they ensure the consistent formatting while working in VSCode.

**Pull request closed without merging**
